---
abstract: 'utilities to build requests for the notifo.com service'
author:
  - 'Pedro Melo <melo@simplicidade.org>'
build_requires:
  Test::Deep: 0
  Test::Exception: 0
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Protocol-Notifo
requires:
  Carp: 0
  File::HomeDir: 0
  File::Spec::Functions: 0
  JSON: 2.26
  MIME::Base64: 0
  URI: 0
  namespace::clean: 0
resources:
  repository: http://github.com/melo/protocol-notifo.git
version: 0.003
